Feature support new spack (#2381)
* Added default generators for Aluminum, Hydrogen, and DiHydrogen.

Cleaned up the center variants for OS X systems.

* Re-added dependency on py-protobuf

* Fix the find cmake config files to work on OS X too.

* Temporarily set the CI pipelines to use the test spack repo.

* Fix the list of dependent modules from spack to only runtime dependencies.

* Updated the minimum spack version to use the CachedCMakeFile versions.

* During cleanup check to the env file before sourcing it.  Allow the cleanup stage to fail.

* Allow the allocation stage to fail on tioga.  Disable subsequent stages if allocation fails.

* Alternate approach to checking for a failed allocation

* Fix multi-line yaml block.

* Moved the test rule of out a script to capture the error code

* Test Gitlab variable FF_USE_NEW_BASH_EVAL_STRATEGY to avoid known bug
in custom executors not getting the correct error code.

* Move the variable to the global environment.

* Starting to cleanup the CI code.

* Trying to set the variable to check the exit code..

* Moved hwloc to a buildable external.  Temporarily removed the upstream spack.

* Another test for fixing CI timeout detection.

* Updating the minimum hash to roll in the spack fix for the concretizer.

* Allowing build tools to be built if necessary.

* Increase the time limits on ROCm systems

* Switched Corona to using mvapich to avoid flux / MPI errors.  Switched back to using the vast upstream mirror.

* Updated Tioga to cray-mpich@2.1.27 and removed the -o pmi=pmix command from flux when using mvapich2 on Corona.

* Switching build script to use as many superbuild external packages as
possible.  Namely, all of the key packages are installed in a shared
location to support more stable CI.

Switched the ROCm 5.7.1 and CUDA 11.8.0.

* Cleaned up the extra Python packages on Pascal and Corona.  Changed
the concretization rule to 'when_possible' versus 'unify' to see if
that addresses the concretization issues on Lassen.

* Disable initialization of DistConv for non-distconv tests

* Finish propagating the LBANN_DISABLE_DISTCONV flag

* Updated the requirements for builds on Lassen.  Added a new variable
for capturing center level root requirements.

Removed the concurrency flag from the concretization since it is all
done together.

* Disabled the disabling of the distconv when not used.

* Removed OpenBLAS requires statement.

* Remove pointers to upstream mirrors.

* Added config flag to force using RPATHs

* Changed CI to not save most of the git directory to avoid mixing stale builds.

* Saved the rules.ninja file so that cleanup commands can run properly.  Also reenabled the unit tests in the lassen distconv build.

diff --git a/.gitlab/common/common.yml b/.gitlab/common/common.yml
--- a/.gitlab/common/common.yml
+++ b/.gitlab/common/common.yml
@@ -63,7 +63,8 @@
     LBANN_CI_RUN_WEEKLY: ${LBANN_CI_RUN_WEEKLY}
 
     # Preserve any spack-build-* directories to allow for faster testing
-    GIT_CLEAN_FLAGS: -ffdx -e spack-build-* -e builds/* -e LBANN_*.cmake -e LBANN_*_setup_build_tools.sh
+    GIT_CLEAN_FLAGS: -ffdx
+#    GIT_CLEAN_FLAGS: -ffdx -e spack-build-* -e builds/* -e LBANN_*.cmake -e LBANN_*_setup_build_tools.sh
   before_script:
     - export SPACK_USER_CACHE_PATH=${SPACK_USER_CACHE_PATH}
     - echo "SPACK_USER_CACHE_PATH=${SPACK_USER_CACHE_PATH}"
@@ -111,15 +112,23 @@
     - echo "export LBANN_BUILD_PARENT_DIR=${LBANN_BUILD_PARENT_DIR}" >> spack-ci-env-name.sh
     - echo "export LBANN_MODFILES_DIR=${LBANN_MODFILES_DIR}" >> spack-ci-env-name.sh
 
-# Cleanup the pipeline's Spack environment.
-# Switching over to reusing Spack environments for each feature branch so don't remove them immediately
-# Cleanup any build directories and spack environments older than 5 days since last use
-.cleanup old spack environment:
+.cleanup old build objects:
+  rules:
+    - exists:
+      - spack-ci-env-name.sh
   script:
     - echo "== CLEAN BUILD DIRECTORY =="
     - source spack-ci-env-name.sh
     - echo "== CLEANING ${LBANN_BUILD_PARENT_DIR}/build =="
     - cmake --build ${LBANN_BUILD_PARENT_DIR}/build --target clean
+
+# Cleanup the pipeline's Spack environment.
+# Switching over to reusing Spack environments for each feature branch so don't remove them immediately
+# Cleanup any build directories and spack environments older than 5 days since last use
+.cleanup old spack environment:
+  script:
+    - echo "== CLEAN CI =="
+    - !reference [.cleanup old build objects, script]
     - echo "== REMOVING BUILD RESOURCES =="
     - find ${CI_PROJECT_DIR}/builds -maxdepth 1 -mtime +2 -name "lbann_*" -type d -print -exec rm -r {} \;
     - find ${CI_PROJECT_DIR} -maxdepth 1 -mtime +2 -name "LBANN_*_setup_build_tools.sh" -type f -print -exec rm {} \;
@@ -129,6 +138,7 @@
     - source ${HOME}/${SPACK_REPO}/share/spack/setup-env.sh
     - find ${CI_PROJECT_DIR} -maxdepth 1 -mtime +5 -name "spack-build-*" -type d -exec rm -r {} \;
     - find ${HOME}/${SPACK_REPO}/var/spack/environments/ -maxdepth 1 -mtime +5 -type d -exec basename {} \; | xargs -r spack env rm --yes-to-all
+  allow_failure: true
 
 .lbann-artifacts:
   artifacts:
@@ -142,6 +152,7 @@
       - builds/lbann_${SYSTEM_NAME}_${SPACK_ENV_BASE_NAME}-*${CI_CONCURRENT_ID}-*/*.cmake
       - builds/lbann_${SYSTEM_NAME}_${SPACK_ENV_BASE_NAME}-*${CI_CONCURRENT_ID}-*/build/CMakeCache.txt
       - builds/lbann_${SYSTEM_NAME}_${SPACK_ENV_BASE_NAME}-*${CI_CONCURRENT_ID}-*/build/build.ninja
+      - builds/lbann_${SYSTEM_NAME}_${SPACK_ENV_BASE_NAME}-*${CI_CONCURRENT_ID}-*/build/CMakeFiles/rules.ninja
       - ${RESULTS_DIR}/*
     exclude:
       - builds/lbann_${SYSTEM_NAME}_${SPACK_ENV_BASE_NAME}-*${CI_CONCURRENT_ID}-*/build/**/*.o
@@ -152,3 +163,25 @@
     - if: $JOB_NAME_SUFFIX == "_distconv"
       when: never
     - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
+
+# .check_allocation:
+#   script:
+#     - |
+#       if [ $FF_USE_NEW_BASH_EVAL_STRATEGY ]; then
+#         echo "== Using the new eval strategy =="
+#       else
+#         echo "== Using the old eval strategy =="
+#       fi
+#     - |
+#       if [ $FF_ENABLE_BASH_EXIT_CODE_CHECK ]; then
+#         echo "== Enable BASH exit code check =="
+#       else
+#         echo "== Not checking the exit code =="
+#       fi
+#     - |
+#       if [ -z "${JOB_ID}" ]; then
+#         echo "== GITLAB FAILED TO GET ALLOCATION - BAIL =="
+#         exit 42
+#       else
+#         echo "== CI JOB RUNNING WITH JOB_ID = $JOB_ID =="
+#       fi
