Alternate approach to checking for a failed allocation

diff --git a/.gitlab/tioga/pipeline.yml b/.gitlab/tioga/pipeline.yml
--- a/.gitlab/tioga/pipeline.yml
+++ b/.gitlab/tioga/pipeline.yml
@@ -57,22 +57,30 @@ allocate lc resources:
     - export FLUX_F58_FORCE_ASCII=t
     - jobid=$(flux --parent alloc -N ${LBANN_NNODES} --exclusive -t ${TEST_TIME} --job-name=${JOB_NAME} --bg)
     - export JOB_ID=$jobid
-    - echo "export JOB_ID=$jobid" > lc_allocation_id.txt
+#    - echo "export JOB_ID=$jobid" > lc_allocation_id.txt
   timeout: 2m
 #  timeout: 6h
   allow_failure: true
 
+.check_allocation:
+  script:
+    - >
+    if [ -z "${JOB_ID}" ]; then
+      echo "== GITLAB FAILED TO GET ALLOCATION - BAIL =="
+      exit 42
+    else
+      echo "== CI JOB RUNNING WITH JOB_ID = ${JOB_ID} =="
+    fi
+
 # Build LBANN and establish the Spack environment for this pipeline.
 build and install:
-  rules:
-    - exists:
-      - lc_allocation_id.txt
   extends:
     - .tioga common
     - .lbann-base-vars
     - .lbann-artifacts
   stage: build
   script:
+    - !reference [.check_allocation, script]
     - echo "== BUILDING LBANN =="
     - export FLUX_F58_FORCE_ASCII=t
     - "export JOB_ID=$(flux jobs -no {id}:{name} | grep ${JOB_NAME} | awk -F: '{print $1}')"
@@ -90,12 +98,12 @@ build and install:
     - export LD_LIBRARY_PATH=${ROCM_PATH}/lib:${LD_LIBRARY_PATH}
     - !reference [.setup_lbann, script]
     - flux proxy ${JOB_ID} .gitlab/common/run-catch-tests-flux.sh
+  allow_failure:
+    exit_codes:
+      - 42
 
 # Run the Python-based unit tests.
 unit tests:
-  rules:
-    - exists:
-      - lc_allocation_id.txt
   extends:
     - .tioga common
     - .lbann-base-vars
@@ -104,6 +112,7 @@ unit tests:
   dependencies:
     - build and install
   script:
+    - !reference [.check_allocation, script]
     - echo "== RUNNING PYTHON-BASED UNIT TESTS =="
     - echo "Testing $(which lbann)"
     - export FLUX_F58_FORCE_ASCII=t
@@ -118,12 +127,12 @@ unit tests:
       - ci_test/unit_tests/results.xml
     reports:
       junit: ci_test/unit_tests/results.xml
+  allow_failure:
+    exit_codes:
+      - 42
 
 # Run the Python-based integration tests.
 integration tests:
-  rules:
-    - exists:
-      - lc_allocation_id.txt
   extends:
     - .tioga common
     - .lbann-base-vars
@@ -134,6 +143,7 @@ integration tests:
   rules:
     - !reference [.lbann-test-rules, rules]
   script:
+    - !reference [.check_allocation, script]
     - echo "== RUNNING PYTHON-BASED INTEGRATION TESTS =="
     - echo "Testing $(which lbann)"
     - export FLUX_F58_FORCE_ASCII=t
@@ -149,12 +159,12 @@ integration tests:
       - ci_test/integration_tests/results.xml
     reports:
       junit: ci_test/integration_tests/results.xml
+  allow_failure:
+    exit_codes:
+      - 42
 
 # This is a dummy job that checks the Catch2 testing.
 check catch2 tests:
-  rules:
-    - exists:
-      - lc_allocation_id.txt
   variables:
     GIT_STRATEGY: none
   extends:
@@ -164,10 +174,14 @@ check catch2 tests:
   dependencies:
     - build and install
   script:
+    - !reference [.check_allocation, script]
     - ([[ $(find ${RESULTS_DIR} -name "catch-tests-failed.txt" | wc -l) -eq 0 ]])
   artifacts:
     reports:
       junit: ${RESULTS_DIR}/*.xml
+  allow_failure:
+    exit_codes:
+      - 42
 
 # Cleanup the pipeline's Spack environment.
 remove spack environment:
