Test Gitlab variable FF_USE_NEW_BASH_EVAL_STRATEGY to avoid known bug in custom executors not getting the correct error code.

diff --git a/.gitlab/tioga/pipeline.yml b/.gitlab/tioga/pipeline.yml
--- a/.gitlab/tioga/pipeline.yml
+++ b/.gitlab/tioga/pipeline.yml
@@ -56,6 +56,7 @@ allocate lc resources:
     - export LBANN_NNODES=$([[ -n "${WITH_WEEKLY}" ]] && echo "4" || echo "2")
     - export FLUX_F58_FORCE_ASCII=t
     - export JOB_ID="UNALLOCATED"
+#    - timeout 30s jobid=$(flux --parent alloc -N ${LBANN_NNODES} --exclusive -t ${TEST_TIME} --job-name=${JOB_NAME} --bg)
     - jobid=$(flux --parent alloc -N ${LBANN_NNODES} --exclusive -t ${TEST_TIME} --job-name=${JOB_NAME} --bg)
     - export JOB_ID=$jobid
 #    - echo "export JOB_ID=$jobid" > lc_allocation_id.txt
@@ -75,28 +76,19 @@ allocate lc resources:
 
 # Build LBANN and establish the Spack environment for this pipeline.
 build and install:
-  # variables:
-  #   ALLOCATED_JOB_ID: "${JOB_ID}"
-  rules:
-    - if: '${JOB_ID} =~ /f*/''
-      when: always
-    # - if: '"${JOB_ID}" == "UNALLOCATED"'
-    #   when: never
-#    - when: always
-    - when: never
   extends:
     - .tioga common
     - .lbann-base-vars
     - .lbann-artifacts
   stage: build
   script:
-    # - |
-    #   if [ -z "$JOB_ID" ]; then
-    #     echo "== GITLAB FAILED TO GET ALLOCATION - BAIL =="
-    #     exit 42
-    #   else
-    #     echo "== CI JOB RUNNING WITH JOB_ID = $JOB_ID =="
-    #   fi
+    - |
+      if [ -z "$JOB_ID" ]; then
+        echo "== GITLAB FAILED TO GET ALLOCATION - BAIL =="
+        exit 42
+      else
+        echo "== CI JOB RUNNING WITH JOB_ID = $JOB_ID =="
+      fi
     # - !reference [.check_allocation, script]
 #    - exit 42
     - echo "== BUILDING LBANN =="
