Starting to cleanup the CI code.

diff --git a/.gitlab/tioga/pipeline.yml b/.gitlab/tioga/pipeline.yml
--- a/.gitlab/tioga/pipeline.yml
+++ b/.gitlab/tioga/pipeline.yml
@@ -64,15 +64,15 @@ allocate lc resources:
 #  timeout: 6h
   allow_failure: true
 
-# .check_allocation:
-#   script:
-#     - |
-#       if [ -z "$JOB_ID" ]; then
-#         echo "== GITLAB FAILED TO GET ALLOCATION - BAIL =="
-#         exit 42
-#       else
-#         echo "== CI JOB RUNNING WITH JOB_ID = $JOB_ID =="
-#       fi
+.check_allocation:
+  script:
+    - |
+      if [ -z "$JOB_ID" ]; then
+        echo "== GITLAB FAILED TO GET ALLOCATION - BAIL =="
+        exit 42
+      else
+        echo "== CI JOB RUNNING WITH JOB_ID = $JOB_ID =="
+      fi
 
 # Build LBANN and establish the Spack environment for this pipeline.
 build and install:
@@ -88,14 +88,14 @@ build and install:
       else
         echo "== Using the old eval strategy =="
       fi
-    - |
-      if [ -z "$JOB_ID" ]; then
-        echo "== GITLAB FAILED TO GET ALLOCATION - BAIL =="
-        exit 42
-      else
-        echo "== CI JOB RUNNING WITH JOB_ID = $JOB_ID =="
-      fi
-    # - !reference [.check_allocation, script]
+    # - |
+    #   if [ -z "$JOB_ID" ]; then
+    #     echo "== GITLAB FAILED TO GET ALLOCATION - BAIL =="
+    #     exit 42
+    #   else
+    #     echo "== CI JOB RUNNING WITH JOB_ID = $JOB_ID =="
+    #   fi
+    - !reference [.check_allocation, script]
 #    - exit 42
     - echo "== BUILDING LBANN =="
     - export FLUX_F58_FORCE_ASCII=t
